### ISSUE TITLE
stderr.get_output() blocks

### ISSUE THREAD

**Issue by jedie** [DiamondLightSource/python-procrunner#19]
* ProcRunner version: 0.9.1
* Python version: 3.6.7
* Operating System: ubuntu

### Description

I call `adb kill-server`, the process ends with exit code 0 but **stderr.get_output()** blocks.

### What I Did

```
DEBUG:procrunner:Starting external process: ('adb', 'kill-server')
DEBUG:procrunner:Process ended after 0.0 seconds with exit code 0 (T-10.00s)* server not running *
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/jens/repos/PyAdbUninstall/adb_uninstall/gui.py", line 341, in reconnect
    self.subprocess("adb", "kill-server")
  File "/home/jens/repos/PyAdbUninstall/adb_uninstall/gui.py", line 309, in subprocess
    args, timeout=timeout, callback_stdout=callback_stdout, callback_stderr=callback_stderr
  File "/home/jens/repos/PyAdbUninstall/.virtualenv/lib/python3.6/site-packages/procrunner/__init__.py", line 492, in run
    stderr = stderr.get_output()

  File "/home/jens/repos/PyAdbUninstall/.virtualenv/lib/python3.6/site-packages/procrunner/__init__.py", line 176, in get_output
    self._thread.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by Anthchirp** [comment]
Could you have a look at bb71233 and see if that fixes it for you?

**Comment by jedie** [comment]
Hm. No it still hangs...
